### ISSUE TITLE
Telegram Bot .Net

### ISSUE THREAD

**Issue by ivanyuwono** [TelegramBots/Telegram.Bot.Examples#173]
Hello,

I have just downloaded the files.  I see that there are 3 project file : 

1. Telegram.WebHook ASP.NET Core project
2. Telegram.Echo Console app
3. Telegram.WebHook Console app

I want to use telegram bot webhook on azure. My understanding are : 

I should host Telegram.WebHook ASP.NET Core project on App Service and upload Telegram.WebHook Console app on Azure WebJob.  Is that true?

Is there any other cheaper solution than using azure?

Thanks

Ivan

**Comment by YLazakovich** [comment]
@ivanyuwono 
The cheapest way it up your ASP.Net core bot by localhost.

Good way if you want to check that your bot work without UP on clouds. You can try use proxy tool like **ngrok**. I used it when tried up bot with ASP.Net core 3.0 and it worked. As result you will have Upped bot and Localhost where you can see documentation info

**Comment by karb0f0s** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. 

Please reopen if you still encounter this issue with the [latest stable version](https://www.nuget.org/packages/Telegram.Bot) and then please use the [issue template](https://raw.githubusercontent.com/TelegramBots/Telegram.Bot/master/.github/ISSUE_TEMPLATE/bug_report.md).
