### ISSUE TITLE
error CS0246: The type or namespace name 'Message' could not be found.

### ISSUE THREAD

**Issue by sirakai-pc** [TelegramBots/Telegram.Bot.Examples#352]
Hello, I followed the guide and the code examples. But it seems that the package Telegram.Bot doesn't have the type/namespace 'Message' anymore. 
Do you have any suggestions about what could be the cause of this issue? That's the only error I get running 'dotnet run'.
```
/home/user/.bin/tgbot/Program.cs(34,4): error CS0246: The type or namespace name 'Message' could not be found (are you missing a using directive or an assembly reference?) [/home/user/.bin/tgbot/TelegramBot.csproj]
/home/user/.bin/tgbot/Program.cs(43,3): error CS0246: The type or namespace name 'Message' could not be found (are you missing a using directive or an assembly reference?) [/home/user/.bin/tgbot/TelegramBot.csproj]
/home/user/.bin/tgbot/Program.cs(49,3): error CS0246: The type or namespace name 'Message' could not be found (are you missing a using directive or an assembly reference?) [/home/user/.bin/tgbot/TelegramBot.csproj]

The build failed. Fix the build errors and run again.
```

**Comment by sirakai-pc** [comment]
**TelegramBot.csproj**:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Telegram.Bot" Version="15.7.1" />
  </ItemGroup>

</Project>

```

**Comment by karb0f0s** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. 

Please reopen if you still encounter this issue with the [latest stable version](https://www.nuget.org/packages/Telegram.Bot) and then please use the [issue template](https://raw.githubusercontent.com/TelegramBots/Telegram.Bot/master/.github/ISSUE_TEMPLATE/bug_report.md).
