### ISSUE TITLE
problem with the Telegram.Bot.Extensions.Polling

### ISSUE THREAD

**Issue by Rourugin** [TelegramBots/Telegram.Bot.Examples#480]
I copied your code and pasted it into the console application after downloading the Telegram Bot library. Maybe I'm doing something wrong? Can you explain to me how you do it step by step please
![2023-08-29 (1)](https://github.com/TelegramBots/Telegram.Bot.Examples/assets/142204688/bafcc814-dcb4-4a36-9f9e-8624d5650777)

**Comment by karb0f0s** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. 

Please reopen if you still encounter this issue with the [latest stable version](https://www.nuget.org/packages/Telegram.Bot) and then please use the [issue template](https://raw.githubusercontent.com/TelegramBots/Telegram.Bot/master/.github/ISSUE_TEMPLATE/bug_report.md).
